Automatically register DataCollectorPlugin
prooph/service-bus-symfony-bundle pull request #38
Opened 2017-10-25 10:07 UTC by UFOMelkor

It will be automatically registered if `kernel.debug = true`.

Is there any case I missed where this behavior is not desirable?

2017-10-25 16:28 UTC, codeliner requested changes

2017-10-25 16:28 UTC, codeliner commented on src/Plugin/DataCollectorPlugin.php
> +            /*$reflClass = new ReflectionClass($bus);
Should we remove this code block? Non active code is confusing. We could create an issue instead.

2017-10-26 08:41 UTC, UFOMelkor commented
I removed the code block. I would think we do not need an issue for this, put perhaps @lunetics might have a look?

2017-10-28 16:51 UTC, codeliner approved these changes

2017-10-28 16:51 UTC, merged