[WIP] Documentation
prooph/service-bus-symfony-bundle pull request #39
Opened 2017-10-25 10:08 UTC by UFOMelkor

2017-10-25 16:49 UTC, codeliner commented
really nice! ping me as soon as the PR is ready for merge

2017-10-27 11:49 UTC, UFOMelkor commented
Ready for review 😃

2017-10-28 17:28 UTC, codeliner requested changes

2017-10-28 17:28 UTC, codeliner commented on doc/getting_started.md
> +(or `config/packages/prooph_service_bus.yml` if you are using flex):
Learned from @chr-hertel and @xabbuh yesterday that Yaml config file extension is now `yaml` (official standard)
So we should change that.

2017-10-28 17:28 UTC, codeliner commented on doc/getting_started.md
> +# app/config/services.yml or (flex) config/packages/prooph_service_bus.yml
s/prooph_service_bus.yml/prooph_service_bus.yaml

2017-10-28 17:28 UTC, codeliner commented on doc/getting_started.md
> +# app/config/config.yml or (flex) config/packages/prooph_service_bus.yml
s/prooph_service_bus.yml/prooph_service_bus.yaml

2017-10-28 17:28 UTC, codeliner commented on doc/routing.md
> +# app/config/config.yml or (flex) config/packages/prooph_service_bus.yml
s/prooph_service_bus.yml/prooph_service_bus.yaml

2017-10-28 17:28 UTC, codeliner commented on doc/routing.md
> +The additional `message` attribute defines the class of the message object that is routed to the handler.
It can also be a custom message name, so maybe: "message attribute defines the message name (message class by default) ..."

2017-10-28 17:28 UTC, codeliner commented on doc/routing.md
> +>     tags: [{ name: 'prooph_service_bus.acme_command_bus.route_target', message_detection: true }]
Nothing to change here, just :+1: for the hint. This is really powerful, thx to Symfony DI

2017-10-29 13:52 UTC, codeliner approved these changes

2017-10-29 13:53 UTC, merged