[WIP] Verify that popo command handlers cannot be automatically detected
prooph/service-bus-symfony-bundle pull request #73
Opened 2018-05-02 06:44 UTC by UFOMelkor

Fixes #72

2018-05-03 20:24 UTC, codeliner requested changes

2018-05-03 20:24 UTC, codeliner commented on doc/routing.md
> +> name of the message is `__invoke`. In both cases the object must be a non abstract class.
s/message/method ?

2018-05-03 20:26 UTC, UFOMelkor commented
Good catch! I'll fix tomorrow 👍🏻

2018-07-15 18:11 UTC, codeliner approved these changes

2018-07-15 18:11 UTC, merged

2018-07-15 18:11 UTC, codeliner commented
sorry, missed the update. Finally merged ;)